# Generated by Django 4.1.4 on 2022-12-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name="Product's name")),
                ('brand', models.CharField(blank=True, max_length=20, verbose_name='Company')),
                ('price', models.FloatField(verbose_name="Product's cost")),
                ('quantity', models.IntegerField(default=1, verbose_name="Product's qty")),
                ('purchase_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
