# Generated by Django 4.1.4 on 2022-12-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='delivery',
            field=models.CharField(default='eligible', max_length=20),
            preserve_default=False,
        ),
    ]
